/*
    PROBLEM STATEMENT: Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with 1 and 2, the first 10 terms will be: 
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
<   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
    even-valued terms.

    EXPLANATION OF CODE:
    - Variables:
        phi[] - The phi array stores two consecutive fibbonaci numbers
        temp  - The temp variable temorarily stores the sum of the consecutive fibonacci numbers
        sum   - The variable sum stores the sum of even fibonacci numbers
    - Logic 
        The code starts with numbers phi[0] = 1 and phi[1] = 1. It adds the two numbers together and stores the value in temp.
        The program then checks if the value in temp is even, if it is then adds the value to sum.
        The code block shifts the fibonaccis values stored by one to the right.
            +-------------------+
            |  phi[0] = phi[1]; |
            |  phi[1] = temp;   |
            +-------------------+    
        What the code does
            -->1  -->1     2   3
        After code block executes we get
               1, -->1, -->2   3  
*/

#include<stdio.h>

#define MAX_NUM 4000000 //Four million

int main(){
    int phi[2];
    int temp = 0;
    int sum = 0;

    phi[0] = 1;
    phi[1] = 1;
    
    do{  
        temp = phi[0] + phi[1];
        phi[0] = phi[1];
        phi[1] = temp;
        if(temp % 2 == 0){
            sum += temp;
        }
    }while(temp < MAX_NUM);
    printf("Sum of even fibonacci numbers (less than four million): %d\n", sum);
}